apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-time
  template:
    metadata:
      labels:
        app: postgres-time
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: test_db
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: root
